#!/usr/bin/env bash
# Checks every hardcoded tool count in the documentation against what the server actually registers,
# and checks docs/reference/tools.md lists exactly the tools that exist.
#
# Counts are derived, never asserted: scripts/print-tool-counts.ts registers the tools against a stub
# server and reports what arrived. Grepping for `defineTool(` would read 116 where the server
# registers 140, because 24 tools are generated by loops over tables.
#
# Matching is by pattern, never by line number: the numbers move whenever a paragraph is added above
# them, and a check pinned to line numbers fails for reasons that have nothing to do with tool counts.
#
# Usage:
#   scripts/check-tool-counts.sh          # verify, exit 1 on mismatch
#   scripts/check-tool-counts.sh --fix    # rewrite the numeric counters in place
set -euo pipefail

cd "$(dirname "$0")/.."

FIX=0
[ "${1:-}" = "--fix" ] && FIX=1

INVENTORY=$(npx tsx scripts/print-tool-counts.ts)
TOTAL=$(jq -r '.total' <<<"$INVENTORY")
GROUP_COUNT=$(jq -r '.groupCount' <<<"$INVENTORY")
SCHEMA_FAILURES=$(jq -r '.jsonSchemaFailures' <<<"$INVENTORY")

# Files carrying a hardcoded total. CHANGELOG.md is excluded: its numbers are historical record.
COUNTER_FILES=(
  README.md
  AGENTS.md
  docker-compose.yml
  docs/index.md
  docs/guide/index.md
  docs/guide/stdio.md
  docs/reference/tools.md
  docs/reference/filtering.md
  docs/contributing/new-tool.md
)

fail=0
note() { printf '  %s\n' "$1"; }

# ── 1. "N tools" everywhere ───────────────────────────────────────────────────
stale_totals=$(grep -roE '\b[0-9]{2,4} tools\b' "${COUNTER_FILES[@]}" | grep -v ":${TOTAL} tools" || true)
if [ -n "$stale_totals" ]; then
  if [ "$FIX" = 1 ]; then
    for f in "${COUNTER_FILES[@]}"; do
      perl -pi -e "s/\b[0-9]{2,4} tools\b/${TOTAL} tools/g" "$f"
    done
    note "fixed: tool totals → ${TOTAL}"
  else
    echo "✗ Stale tool totals (server registers ${TOTAL}):"
    printf '%s\n' "$stale_totals" | sed 's/^/    /'
    fail=1
  fi
fi

# ── 2. "N groups" everywhere ──────────────────────────────────────────────────
stale_groups=$(grep -roE '\b[0-9]{1,3} groups\b' "${COUNTER_FILES[@]}" | grep -v ":${GROUP_COUNT} groups" || true)
if [ -n "$stale_groups" ]; then
  if [ "$FIX" = 1 ]; then
    for f in "${COUNTER_FILES[@]}"; do
      perl -pi -e "s/\b[0-9]{1,3} groups\b/${GROUP_COUNT} groups/g" "$f"
    done
    note "fixed: group counts → ${GROUP_COUNT}"
  else
    echo "✗ Stale group counts (there are ${GROUP_COUNT}):"
    printf '%s\n' "$stale_groups" | sed 's/^/    /'
    fail=1
  fi
fi

# ── 3. Preset tables in filtering.md and AGENTS.md ────────────────────────────
# Rows look like: | `budgeting` | accounts, transactions, … | 44 |
for f in docs/reference/filtering.md AGENTS.md; do
  while IFS= read -r line; do
    preset=$(sed -E 's/^\| *`([a-z]+)`.*/\1/' <<<"$line")
    documented=$(sed -E 's/.*\| *([0-9]+) *\|[[:space:]]*$/\1/' <<<"$line")
    actual=$(jq -r --arg p "$preset" '.presets[$p] // empty' <<<"$INVENTORY")
    [ -z "$actual" ] && continue
    if [ "$documented" != "$actual" ]; then
      if [ "$FIX" = 1 ]; then
        # Replace only the trailing count cell. Rewriting the whole row is how the previous version
        # concatenated old and new (37 + 43 = "3743") instead of substituting.
        LINE="$line" ACTUAL="$actual" perl -i -pe '
          BEGIN { $line = $ENV{LINE}; $actual = $ENV{ACTUAL} }
          if ($_ eq "$line\n") { s/\|\s*\d+\s*\|\s*$/| $actual |\n/ }
        ' "$f"
      else
        echo "✗ $f: preset '$preset' documented as $documented, actually $actual"
        fail=1
      fi
    fi
  done < <(grep -E '^\| *`[a-z]+` *\|.*\| *[0-9]+ *\|' "$f" || true)
done

# ── 4. Group-name lists match TOOL_GROUPS ─────────────────────────────────────
expected_groups=$(jq -r '.groups | keys_unsorted | sort | join(",")' <<<"$INVENTORY")
documented_groups=$(grep -oE '^Valid group names: .*' docs/reference/filtering.md \
  | sed 's/^Valid group names: //' | tr -d '`' | tr ',' '\n' | tr -d ' ' | sort | paste -sd, -)
if [ -n "$documented_groups" ] && [ "$documented_groups" != "$expected_groups" ]; then
  echo "✗ docs/reference/filtering.md: 'Valid group names' does not match TOOL_GROUPS"
  note "documented: $documented_groups"
  note "actual:     $expected_groups"
  fail=1
fi

# ── 5. tools.md lists exactly the registered tools ────────────────────────────
# The most valuable check: catches a tool added without a doc row, and a doc row for a tool that no
# longer exists. This is acceptance criterion "tools.md lists every tool", made mechanical.
documented_tools=$(grep -oE '^\| `[a-z_0-9]+`' docs/reference/tools.md | tr -d '|` ' | sort -u)
# Compared against every tool that exists, not just the default surface: admin-destructive is
# withheld by default but must still be documented.
actual_tools=$(jq -r '.allToolNames[]' <<<"$INVENTORY" | sort -u)
missing_rows=$(comm -13 <(echo "$documented_tools") <(echo "$actual_tools"))
extra_rows=$(comm -23 <(echo "$documented_tools") <(echo "$actual_tools"))
if [ -n "$missing_rows" ]; then
  echo "✗ Registered but absent from docs/reference/tools.md:"
  printf '%s\n' "$missing_rows" | sed 's/^/    /'
  fail=1
fi
if [ -n "$extra_rows" ]; then
  echo "✗ Documented in docs/reference/tools.md but not registered:"
  printf '%s\n' "$extra_rows" | sed 's/^/    /'
  fail=1
fi

# ── 6. Context budget (advisory) ──────────────────────────────────────────────
# Warn only. A preset growing past the budget is a design signal, not a broken build.
BUDGET_TOKENS=25000
for preset in default budgeting; do
  bytes=$(jq -r --arg p "$preset" '.toolsListBytes[$p]' <<<"$INVENTORY")
  tokens=$((bytes / 4))
  if [ "$tokens" -gt "$BUDGET_TOKENS" ]; then
    echo "::warning file=docs/reference/filtering.md::preset '$preset' costs ~${tokens} tokens of tools/list, over the ${BUDGET_TOKENS} budget"
  fi
done

echo
echo "Tools: ${TOTAL} across ${GROUP_COUNT} groups."
jq -r '.presets | to_entries[] | "  \(.key): \(.value) tools"' <<<"$INVENTORY"
echo "tools/list size (approx. tokens):"
jq -r '.toolsListBytes | to_entries[] | "  \(.key): \(.value / 4 | floor)"' <<<"$INVENTORY"
[ "$SCHEMA_FAILURES" -gt 0 ] && echo "  note: ${SCHEMA_FAILURES} input schema(s) could not be converted; sizes are approximate"

if [ "$fail" = 1 ]; then
  echo
  echo "Run 'scripts/check-tool-counts.sh --fix' to update the numeric counters, then review the diff."
  exit 1
fi
exit 0
