#!/usr/bin/env tsx

/**
 * Emits the tool inventory as JSON: totals, per-group and per-preset counts, the full tool-name list,
 * and the serialised size of each preset's `tools/list` response.
 *
 * Counts are taken by registering the tools against a stub server and observing what arrives — the
 * same technique src/tests/tool-filter.test.ts uses. Counting by grepping for `defineTool(` would be
 * wrong: 24 of the tools are generated by loops over tables, so a textual count reads 116 where the
 * server registers 140.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { FireflyClient } from '../src/client.js';
import { PRESETS, registerAllTools, TOOL_GROUPS, type ToolFilterOptions, type ToolGroup } from '../src/tools/index.js';

interface CapturedTool {
  name: string;
  config: {
    title?: string;
    description?: string;
    inputSchema?: Record<string, z.ZodTypeAny>;
    annotations?: Record<string, boolean>;
  };
}

/** Registers tools against a stub server and returns what was registered. */
export function captureTools(options: ToolFilterOptions = {}): CapturedTool[] {
  const tools: CapturedTool[] = [];
  const server = {
    registerTool: (name: string, config: CapturedTool['config']) => tools.push({ name, config }),
    registerPrompt: () => {},
    registerResource: () => {},
  } as unknown as McpServer;
  // The client is never called: registration only reads the schemas.
  registerAllTools(server, {} as FireflyClient, options);
  return tools;
}

let jsonSchemaFailures = 0;

/**
 * Best-effort JSON Schema for one tool's input. Schemas wrapped in `completable()` can fail to
 * convert; rather than abort the whole measurement we substitute a minimal object and count the
 * substitutions, so the reported size stays interpretable instead of silently wrong.
 */
function safeJsonSchema(inputSchema: Record<string, z.ZodTypeAny> | undefined): unknown {
  if (!inputSchema) return { type: 'object', properties: {} };
  try {
    return z.toJSONSchema(z.object(inputSchema), { io: 'input' });
  } catch {
    jsonSchemaFailures++;
    return { type: 'object', properties: Object.fromEntries(Object.keys(inputSchema).map((k) => [k, {}])) };
  }
}

/** Approximates the bytes an MCP client receives for `tools/list` at this preset. */
function toolsListBytes(tools: readonly CapturedTool[]): number {
  return JSON.stringify({
    tools: tools.map(({ name, config }) => ({
      name,
      title: config.title,
      description: config.description,
      annotations: config.annotations,
      inputSchema: safeJsonSchema(config.inputSchema),
    })),
  }).length;
}

export interface ToolInventory {
  total: number;
  groupCount: number;
  groups: Record<string, number>;
  presets: Record<string, number>;
  presetGroups: Record<string, string[]>;
  toolsListBytes: Record<string, number>;
  toolNames: string[];
  jsonSchemaFailures: number;
}

export function inventory(): ToolInventory {
  const all = captureTools();

  const groups: Record<string, number> = {};
  for (const group of TOOL_GROUPS) {
    groups[group] = captureTools({ groups: [group as ToolGroup] }).length;
  }

  const presets: Record<string, number> = {};
  const presetGroups: Record<string, string[]> = {};
  const bytes: Record<string, number> = {};
  for (const name of Object.keys(PRESETS)) {
    const tools = captureTools({ preset: name });
    presets[name] = tools.length;
    presetGroups[name] = [...PRESETS[name]];
    bytes[name] = toolsListBytes(tools);
  }

  return {
    total: all.length,
    groupCount: TOOL_GROUPS.length,
    groups,
    presets,
    presetGroups,
    toolsListBytes: bytes,
    toolNames: all.map((t) => t.name).sort(),
    jsonSchemaFailures,
  };
}

// Only emit when run directly, so the module stays importable from tests.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop() ?? '')) {
  console.log(JSON.stringify(inventory(), null, 2));
}
